sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - easy_install -U setuptools
    - pip install "ipython<6.0"
    - pip install .
    - pip install -r test_requirements.txt
    - pip install pytest-cov
    - pip install coveralls
script:
    - py.test --cov ipythonblocks --cov-report term-missing
after_success:
    - coveralls
